# Filters applied to RFDiffusion backbone outputs.
# Each plugin script should define a `filter_backbone(pdb: str | Path, kwargs: dict)` function
# that returns True (pass) or False (fail) for a given structure.

rfdiff_backbone_filters:
  # === Neighbor Count Filter ===
  # Keeps structures only if the number of *non-scaffold* residues within 8Å of the first helix
  # (in chain A) falls within the specified range. Excludes residues from chain B (scaffold).
  - filter_name: num_neighbors
    filter_script: plugins/num_neighbors.py
    delete_failed: false           # If False, failed structures are moved to 'failed_filters/'
    min_num_neighbors: 7         # Lower bound on allowed neighbor count
    max_num_neighbors: 50         # Upper bound on allowed neighbor count
    neighbor_distance: 8.0        # Ångström distance for detecting neighboring residues
    

  # === Clash Detection Filter ===
  # Assembles the structure into a C8 symmetry using the provided base PDB.
  # Rejects structures if any inter-chain atom-atom distance is below clash_distance.
  - filter_name: clash_check
    filter_script: plugins/clash_check.py
    delete_failed: false
    base_pdb: "/home/d12-studenti/Kiyan/prosculpt_projects/Fibers/Roller_fuse/input_structures/2B12.pdb"    # Full path to the base scaffold used for alignment
    residues_to_align: 85                # Number of residues at end of chain A to align
    clash_distance: 1                  # Ångström threshold for detecting steric clashes
    skip_last_residues: 100       #skip last N residues from clash check